branches:
  only:
  - posts
  - themes
  - hexo

language: node_js

sudo: false

node_js:
- '5.1'

before_install:
# - openssl aes-256-cbc -K $encrypted_26b4962af0e7_key -iv $encrypted_26b4962af0e7_iv
#   -in doc/travis.enc -out ~/.ssh/id_rsa -d
# - chmod 600 ~/.ssh/id_rsa
# - eval $(ssh-agent)
# - ssh-add ~/.ssh/id_rsa
# - cp doc/ssh_config ~/.ssh/config
- git config --global user.name "heymind"
- git config --global user.email heymind@outlook.com

install:	
- npm install hexo-cli -g

script:
- bash script